### ISSUE TITLE
Internationalisation at jsGanttImproved/ng-gantt

### ISSUE THREAD

**Issue by yeheshuah** [jsGanttImproved/ng-gantt#11]
Does internationalisation works at [jsGanttImproved/ng-gantt](https://github.com/jsGanttImproved/ng-gantt).

According to the [internationalisation specification](https://github.com/jsGanttImproved/jsgantt-improved/blob/master/Documentation.md#-internationalisation) it looks like there is internationalisation functionality, but how to use it?

Thanks in advance.

---

Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: 7.2.13

jsgantt-improved: ^2.2.11
ng-gantt: ^2.1.0

**Comment by mariohmol** [comment]
does it works for u?

https://github.com/jsGanttImproved/ng-gantt/blob/master/src/app/demo/demo.component.ts#L146

**Comment by yeheshuah** [comment]
> does it works for u?
> 
> https://github.com/jsGanttImproved/ng-gantt/blob/master/src/app/demo/demo.component.ts#L146

Nope...

[demo.component.ts#L146](https://github.com/jsGanttImproved/ng-gantt/blob/edf3d23eac0d9edf707650b97a9ec9e8bc1ddf0a/src/app/demo/demo.component.ts#L146) is just setting up current language, isn't it? Otherwise, what language should be used. But, how to set up language content like [here](https://github.com/jsGanttImproved/ng-gantt/blob/edf3d23eac0d9edf707650b97a9ec9e8bc1ddf0a/src/app/demo/demo.component.ts#L153) at comented out code.

**Comment by mariohmol** [comment]
check this line... `https://github.com/jsGanttImproved/ng-gantt/blob/edf3d23eac0d9edf707650b97a9ec9e8bc1ddf0a/src/app/demo/demo.component.html#L4`

basically.. you can put in on options ` this.editorOptions = { vLang: 'en' }`

**Comment by yeheshuah** [comment]
> check this line... `https://github.com/jsGanttImproved/ng-gantt/blob/edf3d23eac0d9edf707650b97a9ec9e8bc1ddf0a/src/app/demo/demo.component.html#L4`
> 
> basically.. you can put in on options ` this.editorOptions = { vLang: 'en' }`

For example, I want to add Japanese localisation.
Yes, I can setup ` this.editorOptions = { vLang: 'ja' }`,
but how can I setup key-values listed in [Internationalisation documentation](https://github.com/jsGanttImproved/jsgantt-improved/blob/master/Documentation.md#-internationalisation)?

**Comment by mariohmol** [comment]
gotcha..  we need a ja translation...

see this file

https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/lang.ts

can u make a translation for your language for us?

**Comment by yeheshuah** [comment]
> gotcha.. we need a ja translation...
> 
> see this file
> 
> https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/lang.ts

Great!

> can u make a translation for your language for us?

Yes, I can.
When I make a translation, I will create pull request.

**Comment by mariohmol** [comment]
@yeheshuah make for us =)

**Comment by mariohmol** [comment]
Closing this issue and putting in jgantt-improved 

https://github.com/jsGanttImproved/jsgantt-improved/issues/241

**Comment by mariohmol** [comment]
released on new version thanks to @yeheshuah

**Comment by luk3skyw4lker** [comment]
Does it have support for pt-BR language? I can't use addLang to add it to the language options.

**Comment by luk3skyw4lker** [comment]
Found it already, thanks!
