### ISSUE TITLE
Compatibility with angular 7

### ISSUE THREAD

**Issue by shradhakarnawat** [jsGanttImproved/ng-gantt#26]
I want to integrate this with my **angular 7** application, but
On line -
_@ViewChild(GanttEditorComponent,{ static:true }) editor: GanttEditorComponent;_

I got an error "_Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
(property) static: boolean_"

So, when I change it to -
_@ViewChild(GanttEditorComponent) editor: GanttEditorComponent;_
I get following error -
ERROR Error: "Uncaught (in promise): Error: Can't resolve all parameters for SchedularComponent: ([object Object], ?, [object Object]).
syntaxError@http://localhost:4200/vendor.js:16940:22
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getDependenciesMetadata@http://localhost:4200/vendor.js:33494:35
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getTypeMetadata@http://localhost:4200/vendor.js:33387:26
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNonNormalizedDirectiveMetadata@http://localhost:4200/vendor.js:33006:24
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getEntryComponentMetadata@http://localhost:4200/vendor.js:33590:28
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getEntryComponentsFromProvider/<@http://localhost:4200/vendor.js:33581:31
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getEntryComponentsFromProvider@http://localhost:4200/vendor.js:33580:30
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getProvidersMetadata/<@http://localhost:4200/vendor.js:33553:138
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getProvidersMetadata@http://localhost:4200/vendor.js:33516:19
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getProvidersMetadata/<@http://localhost:4200/vendor.js:33518:23
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype._getProvidersMetadata@http://localhost:4200/vendor.js:33516:19
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleMetadata/<@http://localhost:4200/vendor.js:33139:118
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleMetadata@http://localhost:4200/vendor.js:33130:49
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleSummary@http://localhost:4200/vendor.js:33065:35
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleMetadata/<@http://localhost:4200/vendor.js:33152:55
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleMetadata@http://localhost:4200/vendor.js:33130:49
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._loadModules@http://localhost:4200/vendor.js:40539:51
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileModuleAndComponents@http://localhost:4200/vendor.js:40520:36
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype.compileModuleAsync@http://localhost:4200/vendor.js:40480:37
./node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js/CompilerImpl.prototype.compileModuleAsync@http://localhost:4200/vendor.js:73464:31
./node_modules/@angular/core/fesm5/core.js/SystemJsNgModuleLoader.prototype.loadAndCompile/<@http://localhost:4200/vendor.js:60357:60
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:7698:26
onInvoke@http://localhost:4200/vendor.js:59294:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:7697:52
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://localhost:4200/polyfills.js:7457:43
scheduleResolveOrReject/<@http://localhost:4200/polyfills.js:8196:34
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:7730:31
onInvokeTask@http://localhost:4200/vendor.js:59285:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:7729:60
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.js:7502:47
drainMicroTaskQueue@http://localhost:4200/polyfills.js:7908:35

How do I integrate it with my angular 7 application?

**Comment by mariohmol** [comment]
Hi i'm sorry, we are supporting 8+ angular.. I just did an update now that supports ang10
