### ISSUE TITLE
Any click event on the gantt chart?

### ISSUE THREAD

**Issue by herrgeorgewenbinwang** [jsGanttImproved/ng-gantt#27]
Do you have the click event on the bar of gantt chart? if I select one task and I would like to open another detail panel. thanks, George

**Comment by mariohmol** [comment]
Yes, there is a lot of events that you can configure on ngGantt

Check in this example by vEvents

https://github.com/jsGanttImproved/jsgantt-improved/blob/master/Documentation.md
