### ISSUE TITLE
vEvent

### ISSUE THREAD

**Issue by herrgeorgewenbinwang** [jsGanttImproved/ng-gantt#30]
Hi,
i almost customized ng-gantt all and nearly done in my project. but the issue is the vEvent is not working. the vEvent is triggered, but all the current data is missing. seems like the parents component ts is not pass in. when the test method called, the original value of orderNumber is missing. can anybody help?

many thanks,
George

 vEvents: {
        taskname: this.test, 
        beforeDraw: () => console.log('before draw listener'),
        afterDraw: () => console.log('before after listener')
      },
test(event) { 
    this._orderNumber = "dfgls";
    this._currentJobVisitOrDefect = 'po';
    this._currentDefectID = event.getAllData().pDataObjec.DefectID; 
    alert(event.getAllData().pDataObjec.pID); 
  }

**Comment by ansalian** [comment]
I am facing the same issue, with vEvents not working..  @herrgeorgewenbinwang Did you manage to find a solution, by any chance?

**Comment by mariohmol** [comment]
Hi, I included an example on the stackblitz using this function

https://stackblitz.com/edit/angular-ng-gantt
