### ISSUE TITLE
How can I hide particular column?

### ISSUE THREAD

**Issue by poddarkhushbu07** [jsGanttImproved/ng-gantt#34]
I saw method named : **setShowComp** in jsgantt-improved documentation, but I am not getting how to use this method in angular with ng-gantt.

**Comment by pasha42** [comment]
@poddarkhushbu07 In the [jsganttImproved](https://github.com/jsGanttImproved/jsgantt-improved/blob/master/Documentation.md) documentations, there is an method naming setShowComp.

You can refer to the following component file from the demo folder [demo.component.ts](https://github.com/jsGanttImproved/ng-gantt/blob/master/src/app/demo/demo.component.ts). It's having some basic options already configured with the editor. (Refer line no 71 in the file)
![image](https://user-images.githubusercontent.com/40499944/95014913-bd2a5b80-0667-11eb-8ad6-37f7866ba6a5.png)


- vShowComp - Show Completion
- vShowRes - Show Resource and so on

The value assigned to these variables can be 0 (Hide) and 1 (Show).

**Comment by mariohmol** [comment]
thanks @pasha42 

If there is something else feel free to reopen
