### ISSUE TITLE
How to redraw the chart on data change?

### ISSUE THREAD

**Issue by vishal-shetty** [jsGanttImproved/ng-gantt#38]
When the data is updated, like from a modal popup then the chart is not redrawn. I saw there is a method g.draw() in the documentation for pure javascript but what method to call in angular to redraw the chart when the data has got updated from another component.

**Comment by mariohmol** [comment]
Hi, I did an example here redrawing.. check it out 

https://stackblitz.com/edit/angular-ng-gantt?file=src%2Fapp%2Fapp.component.ts
