### ISSUE TITLE
Timelines

### ISSUE THREAD

**Issue by fernandortdias** [jsGanttImproved/ng-gantt#4]
Is there anyway to have two or more tasks or milestones in the same line, as timelines, each one with their own attributes, links to other tasks included?

**Comment by mariohmol** [comment]
can u provide a image and an example data explaining this?

**Comment by fernandortdias** [comment]
Hi.
You may think of it as a timeline, as in the "advanced" example below:
Timelines | Charts | Google Developers


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Timelines | Charts | Google Developers


 |

 |

 |



Or you may think of it as "split tasks", as in MS-Project, but what I am looking for is not the same thing. I would like to be able to show a set of tasks on after another, ate the same line, although each one of them are individual tasks, with their links to other tasks, their dates, resources, etc. 
That would be useful in order to "compress" project schedules that have sets of tasks that depend on each other sequentially, like the one below.


One easy workaround it to use Summary tasks, like this:




... but when you collapse the project schedule to sumamry tasks, it would be useful to see the task names as text inside the bars or as independent floating tips for each task, and each task could be shown with its on dates and colors.
What do you think? Is it a requirement that is too specific? 
Regards, Fernando Dias
 

    Em quarta-feira, 12 de dezembro de 2018 21:45:41 AMST, Mario Mol <notifications@github.com> escreveu:  
 
 
can u provide a image and an example data explaining this?

**Comment by mariohmol** [comment]
Yes.. this seems to be too specific.. cause its not usual to have this in a gantt chart..

https://www.telerik.com/forums/show-multiple-tasks-on-one-line-in-gantt-view

You can suggest this feature in this repo : https://github.com/jsGanttImproved/jsgantt-improved


What i suggest to you its to use groups and collapse them to look smaller
