### ISSUE TITLE
Support for Angular 10 and 11

### ISSUE THREAD

**Issue by ajeeth-rajamany-tm** [jsGanttImproved/ng-gantt#42]
Hello,
Would ng-gantt work with Angular 10.x and 11.x ? We are using 10.x and 11.x and would like to try out ng-gantt

**Comment by TalhaAlshafeey** [comment]
any updates?

**Comment by mariohmol** [comment]
Alright, we will try to bump manually, if it wont work, we can try to port to a new model using ang14

https://medium.com/@joosep.parts/create-an-angular-14-library-use-it-locally-when-developing-and-publish-the-package-to-npm-689ca2efdea8

https://github.com/Nurech/ngx-everything-uppercase-lib/tree/master/projects/ngx-everything-uppercase/src

**Comment by mariohmol** [comment]
this is now supported on ang10, could  u please double check?
