### ISSUE TITLE
vEventClickRow not working after chart is redrawn on data change

### ISSUE THREAD

**Issue by poddarkhushbu07** [jsGanttImproved/ng-gantt#44]
Check out this code:
https://stackblitz.com/edit/angular-ng-gantt-jbbno7?devtoolsheight=33

After data is reloaded, events doesnt work.

**Comment by poddarkhushbu07** [comment]
@mariohmol Please check and revert on this issue.

**Comment by mariohmol** [comment]
Hi, are u still with this issue?
in this link example when I click I receive the console log..

lmk if I can help
