### ISSUE TITLE
Angular 12 How to get the Selected task data on individual task click 

### ISSUE THREAD

**Issue by neha18saxena** [jsGanttImproved/ng-gantt#45]
Hi Team,

Angular 12 How to get the Selected task data on individual task click .Can you please suggest which event is require to implement.I have gone through on existing issues but not able to get it . how to do  this.Is this doable using this library or Not?
My sample code
  <ng-gantt
                          [options]="editorOptions"
                          [data]="data"
                          #editor (click)="test($event)"                         
                        ></ng-gantt>

**Comment by poddarkhushbu07** [comment]
@neha18saxena, 

To handle click on each individual entry, use **vEventClickRow** event of options

```
 this.editorOptions = {
                vFormat: 'week',
                vEditable: false,
                vShowComp: 0,
                vShowTaskInfoLink: 0,
                vShowTaskInfoNotes: 0,
                vEventClickRow: (e) => {
                   console.log(e.getAllData());
                }
            };
```

**Comment by mariohmol** [comment]
Thanks @poddarkhushbu07  =)
