### ISSUE TITLE
Is it possible to add custom language (Angular 8+)? Need ukraininan lang

### ISSUE THREAD

**Issue by ilona257** [jsGanttImproved/ng-gantt#51]
Is it possible to add custom language (Angular 8+)? Need ukraininan lang
ua = {
    'january': 'Січень',
    'february': 'Лютий',
    'march': 'Березень',
    'april': 'Квітень',
    'maylong': 'Травень',
    'june': 'Червень',
    'july': 'Липень',
    'august': 'Серпень',
    'september': 'Вересень',
    'october': 'Жовтень',
    'november': 'Листопад',
    'december': 'Грудень',
    'jan': 'Січ',
    'feb': 'Лют',
    'mar': 'Бер',
    'apr': 'Кві',
    'may': 'Тра',
    'jun': 'Чер',
    'jul': 'Лип',
    'aug': 'Сер',
    'sep': 'Вер',
    'oct': 'Жов',
    'nov': 'Лис',
    'dec': 'Гру',
    'sunday': 'Неділя',
    'monday': 'Понеділок',
    'tuesday': 'Вівторок',
    'wednesday': 'Середа',
    'thursday': 'Четвер',
    'friday': 'П\'ятниця',
    'saturday': 'Субота',
    'sun': '	Нд',
    'mon': 'Пн',
    'tue': '	Вт',
    'wed': 'Ср',
    'thu': '	Чт',
    'fri': '	Пт',
    'sat': '	Сб',
    'res': 'Ресурс',
    'dur': 'Тривалість',
    'comp': '% виконання',
    'completion': 'Виконано',
    'startdate': 'Поч. дата',
    'planstartdate': 'План Поч. дата',
    'enddate': 'Кін. дата',
    'planenddate': 'План Кін. дата',
    'cost': 'Вартість',
    'moreinfo': 'Деталі',
    'nodata': 'Нічого не знайдено',
    'notes': 'Нотатки',
    'format': 'Формат',
    'hour': 'Година',
    'day': 'День',
    'week': 'Тиждень',
    'month': 'Місяць',
    'quarter': 'Кварт',
    'hours': 'Годин',
    'days': 'Днів',
    'weeks': 'Тижнів',
    'months': 'Місяців',
    'quarters': 'Кварталів',
    'hr': 'г.',
    'dy': 'дн.',
    'wk': 'тиж.',
    'mth': 'міс.',
    'qtr': 'кв.',
    'hrs': 'г.',
    'dys': 'дн.',
    'wks': 'тиж.',
    'mths': 'міс.',
    'qtrs': 'кв.',
    'tooltipLoading': 'Загрузка...'
  }

**Comment by mariohmol** [comment]
Hi, added on jsgantt-improved the language.. see if updating there works for you

https://github.com/jsGanttImproved/jsgantt-improved/pull/371

If not let me know

thanks for the translation

**Comment by ilona257** [comment]
It works! Thank you very much!

**Comment by ilona257** [comment]
Made a mistake in one word, instead of 'week': 'Неділя' -> 'week': 'Тиждень' , if possible, correct it, please

**Comment by mariohmol** [comment]
Fixed in jsgantt-improved v2.8.10 — the Ukrainian translation for `week` was corrected from `'Неділя'` (Sunday) to `'Тиждень'` (week).
