### ISSUE TITLE
default option of 'Week' to 'Day'

### ISSUE THREAD

**Issue by mahsayedsalem** [jsGanttImproved/ng-gantt#7]
How to change the default loading option of the gantt chart from showing the 'Week' tab to the 'Day' tab. 

Also how can I remove everything but the 'Day' tab?

**Comment by BlackTango** [comment]
I tried too and never succeed. Now i just leave it to week.

**Comment by mariohmol** [comment]
check it out https://github.com/jsGanttImproved/ng-gantt/blob/master/src/app/demo/demo.component.ts#L125

**Comment by mariohmol** [comment]
have this working with stackblitz as well..

https://stackblitz.com/edit/angular-ng-gantt?file=src%2Fapp%2Fapp.component.ts

update to latest  please

**Comment by shubhaangiK** [comment]
hey can I add only start date as editable field in chart and rest read only @mariohmol

**Comment by mariohmol** [comment]
Hi @shubhaangiK I think we have just the editable true or false, but it could receive an object with the editable fields, could u open an issue for that? thanks!

**Comment by shubhaangiK** [comment]
yes but setting vEditable true or false is making all the fields editable
or non editable, i just want to keep pstart and pend, pComp editable not
pName
