### ISSUE TITLE
vScrollTo not working

### ISSUE THREAD

**Issue by BlackTango** [jsGanttImproved/ng-gantt#8]
I'm trying to make the option vScrollTo to work but its never working. 

This is my options setting: 

`editorOptions = {
    vScrollTo: "today",
  }`

and to set the options i'm using : 
`    this.editor.setOptions(this.editorOptions)
`

That being said, its not working.

**Comment by mariohmol** [comment]
dup to #9

**Comment by BlackTango** [comment]
Hi, thank you for your reply. 

It still don't work. 

I read the stack blitz you wrote for the other issue. But you did not added the options.

I strongly think there is an error with this specific setting as i cannot make it work. 
I'm still trying. 
I went in the GanttEditorComponent definition and made the editor property public so i can directly use the editor.setScrollTo("today") function. This still don't work. I think angular is not letting gantt take control of scrolling anything.

**Comment by mariohmol** [comment]
are u using this  versions?

```
   "jsgantt-improved": "^2.2.6",
    "ng-gantt": "^2.1.0",
```

**Comment by BlackTango** [comment]
I updated the version, It worked. 
Thank you!
